[package]
name = "hubd"
version = "0.4.2"
edition = "2021"
authors = ["AERL Pty. Ltd."]
license = "none"
readme = false

[features]
default = ["canbus", "modbus"]
canbus = ["dep:socketcan"]
modbus = ["dep:tokio-modbus", "dep:bitter"]
web = ["dep:rust-embed", "dep:mime_guess"]

[dependencies]
env_logger = "0.11.1"
futures = "0.3"
log = "0.4.17"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
socketcan = { version = "2.0.0", default-features = false, optional = true }
tokio = { version = "1.0", features = ["full"] }
prost-types = "0.12.0"
reqwest = { version = "0.11.16", default-features = false, features = ["json", "rustls-tls"] }
lazy_static = "1.4.0"
pnet_datalink = "0.34.0"
prost = "0.12.0"
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive", "env"] }
rand = "0.8.5"
tokio-modbus = {version = "0.9.0", optional = true}
typify = "0.0.15"
postgrest = "1.6.0"
tokio-serial = "5.4.4"
libsqlite3-sys = { version = "0.27.0", features = ["bundled"] }
axum = "0.7.2"
rust-embed = {version = "8.0.0", optional = true }
mime_guess = {version = "2.0.4", optional = true }
bitter = {version = "0.6.2", optional = true }

[build-dependencies]
anyhow = "1.0.71"
prost-build = "0.12.0"
protobuf-src = "1.1.0"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = true

[package.metadata.deb]
maintainer = "AERL Pty. Ltd. <support@aerl.com.au>"
copyright = "AERL Pty. Ltd. © 2024"
section = "utils"
priority = "optional"
maintainer-scripts = "debian/"
systemd-units = { enable = true }
assets = [
    ["target/release/hubd", "usr/bin/hubd", "755"],
    ["assets/default_environment", "/etc/default/hubd", "644"],
]
