drop policy "Allow SELECT for all devices (bypass)" on "public"."modbus_device";

alter table "public"."modbus_interface" drop constraint "modbus_interface_config_check";

alter table "public"."modbus_interface" drop constraint "modbus_interface_device_id_fkey";

create table "public"."device_schema" (
    "device_name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "device_type" text not null,
    "id" bigint generated by default as identity not null,
    "schema" json not null
);


alter table "public"."device_schema" enable row level security;

create table "public"."device_type_schema" (
    "created_at" timestamp with time zone not null default now(),
    "version" bigint not null default '0'::bigint,
    "name" text not null,
    "schema" json not null
);


alter table "public"."device_type_schema" enable row level security;

create table "public"."gateway_network_state" (
    "id" text not null,
    "updated_at" timestamp with time zone not null default now(),
    "state" json not null default '{}'::json
);


alter table "public"."gateway_network_state" enable row level security;

alter table "public"."modbus_device" add column "gateway_id" text;

alter table "public"."modbus_device" alter column "slave_id" drop not null;

alter table "public"."modbus_interface" drop column "device_id";

alter table "public"."modbus_interface" add column "gateway_id" bigint not null;

alter table "public"."modbus_product" add column "product_id" bigint;

CREATE UNIQUE INDEX device_schema_device_name_key ON public.device_schema USING btree (device_name);

CREATE UNIQUE INDEX device_schema_id_key ON public.device_schema USING btree (id);

CREATE UNIQUE INDEX device_schema_pkey ON public.device_schema USING btree (id);

CREATE UNIQUE INDEX device_type_schema_pkey ON public.device_type_schema USING btree (name);

CREATE UNIQUE INDEX gateway_network_state_pkey ON public.gateway_network_state USING btree (id);

alter table "public"."device_schema" add constraint "device_schema_pkey" PRIMARY KEY using index "device_schema_pkey";

alter table "public"."device_type_schema" add constraint "device_type_schema_pkey" PRIMARY KEY using index "device_type_schema_pkey";

alter table "public"."gateway_network_state" add constraint "gateway_network_state_pkey" PRIMARY KEY using index "gateway_network_state_pkey";

alter table "public"."device_schema" add constraint "device_schema_device_name_key" UNIQUE using index "device_schema_device_name_key";

alter table "public"."device_schema" add constraint "device_schema_id_key" UNIQUE using index "device_schema_id_key";

alter table "public"."device_schema" add constraint "public_device_schema_device_type_fkey" FOREIGN KEY (device_type) REFERENCES device_type_schema(name) ON UPDATE CASCADE ON DELETE RESTRICT not valid;

alter table "public"."device_schema" validate constraint "public_device_schema_device_type_fkey";

alter table "public"."gateway_network_state" add constraint "public_gateway_network_state_id_fkey" FOREIGN KEY (id) REFERENCES gateways(hub_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."gateway_network_state" validate constraint "public_gateway_network_state_id_fkey";

alter table "public"."modbus_device" add constraint "modbus_device_gateway_id_fkey" FOREIGN KEY (gateway_id) REFERENCES hub(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."modbus_device" validate constraint "modbus_device_gateway_id_fkey";

alter table "public"."modbus_interface" add constraint "modbus_interface_gateway_id_fkey" FOREIGN KEY (gateway_id) REFERENCES gateways(id) ON DELETE CASCADE not valid;

alter table "public"."modbus_interface" validate constraint "modbus_interface_gateway_id_fkey";

alter table "public"."modbus_product" add constraint "public_modbus_product_product_id_fkey" FOREIGN KEY (product_id) REFERENCES device_schema(id) ON UPDATE CASCADE not valid;

alter table "public"."modbus_product" validate constraint "public_modbus_product_product_id_fkey";

grant delete on table "public"."device_schema" to "anon";

grant insert on table "public"."device_schema" to "anon";

grant references on table "public"."device_schema" to "anon";

grant select on table "public"."device_schema" to "anon";

grant trigger on table "public"."device_schema" to "anon";

grant truncate on table "public"."device_schema" to "anon";

grant update on table "public"."device_schema" to "anon";

grant delete on table "public"."device_schema" to "authenticated";

grant insert on table "public"."device_schema" to "authenticated";

grant references on table "public"."device_schema" to "authenticated";

grant select on table "public"."device_schema" to "authenticated";

grant trigger on table "public"."device_schema" to "authenticated";

grant truncate on table "public"."device_schema" to "authenticated";

grant update on table "public"."device_schema" to "authenticated";

grant delete on table "public"."device_schema" to "service_role";

grant insert on table "public"."device_schema" to "service_role";

grant references on table "public"."device_schema" to "service_role";

grant select on table "public"."device_schema" to "service_role";

grant trigger on table "public"."device_schema" to "service_role";

grant truncate on table "public"."device_schema" to "service_role";

grant update on table "public"."device_schema" to "service_role";

grant delete on table "public"."device_type_schema" to "anon";

grant insert on table "public"."device_type_schema" to "anon";

grant references on table "public"."device_type_schema" to "anon";

grant select on table "public"."device_type_schema" to "anon";

grant trigger on table "public"."device_type_schema" to "anon";

grant truncate on table "public"."device_type_schema" to "anon";

grant update on table "public"."device_type_schema" to "anon";

grant delete on table "public"."device_type_schema" to "authenticated";

grant insert on table "public"."device_type_schema" to "authenticated";

grant references on table "public"."device_type_schema" to "authenticated";

grant select on table "public"."device_type_schema" to "authenticated";

grant trigger on table "public"."device_type_schema" to "authenticated";

grant truncate on table "public"."device_type_schema" to "authenticated";

grant update on table "public"."device_type_schema" to "authenticated";

grant delete on table "public"."device_type_schema" to "service_role";

grant insert on table "public"."device_type_schema" to "service_role";

grant references on table "public"."device_type_schema" to "service_role";

grant select on table "public"."device_type_schema" to "service_role";

grant trigger on table "public"."device_type_schema" to "service_role";

grant truncate on table "public"."device_type_schema" to "service_role";

grant update on table "public"."device_type_schema" to "service_role";

grant delete on table "public"."gateway_network_state" to "anon";

grant insert on table "public"."gateway_network_state" to "anon";

grant references on table "public"."gateway_network_state" to "anon";

grant select on table "public"."gateway_network_state" to "anon";

grant trigger on table "public"."gateway_network_state" to "anon";

grant truncate on table "public"."gateway_network_state" to "anon";

grant update on table "public"."gateway_network_state" to "anon";

grant delete on table "public"."gateway_network_state" to "authenticated";

grant insert on table "public"."gateway_network_state" to "authenticated";

grant references on table "public"."gateway_network_state" to "authenticated";

grant select on table "public"."gateway_network_state" to "authenticated";

grant trigger on table "public"."gateway_network_state" to "authenticated";

grant truncate on table "public"."gateway_network_state" to "authenticated";

grant update on table "public"."gateway_network_state" to "authenticated";

grant delete on table "public"."gateway_network_state" to "service_role";

grant insert on table "public"."gateway_network_state" to "service_role";

grant references on table "public"."gateway_network_state" to "service_role";

grant select on table "public"."gateway_network_state" to "service_role";

grant trigger on table "public"."gateway_network_state" to "service_role";

grant truncate on table "public"."gateway_network_state" to "service_role";

grant update on table "public"."gateway_network_state" to "service_role";

create policy "Allow devices to read rows with their ID"
on "public"."modbus_device"
as permissive
for select
to device
using (((auth.jwt() ->> 'hub'::text) = gateway_id));



